language: ruby
sudo: false
rvm:
  - 2.3.0
cache:
  bundler
env:
  matrix:
    - EMACS_VERSION=24.5
    - EMACS_VERSION=snapshot
    - TEXINFO_VERSION=6.0
before_install:
  - export PATH="$HOME/bin:$PATH"
script:
  - if [[ -n $EMACS_VERSION ]]; then make -f emacs-travis.mk install_emacs; fi
  - if [[ -n $TEXINFO_VERSION ]]; then make -f emacs-travis.mk install_texinfo; fi
  - bundle exec rspec --color --format doc
